const list = [
  "Action",
  "Beat 'em up",
  "Hack and slash",
  "Fighting",
  "Platform",
  "Shooter",
  "Survival",
  "Battle royale",
  "Action-adventure",
  "Stealth",
  "Adventure",
  "Interactive fiction",
  "Interactive movie",
  "Visual novel",
  "Gacha",
  "Horror",
  "Survival horror",
  "Masocore",
  "Massively multiplayer online",
  "Role-playing",
  "Action role-playing",
  "Tactical role-playing",
  "Simulation",
  "Construction and management",
  "Life simulation",
  "Sports",
  "Vehicle",
  "Strategy",
  "4X",
  "Auto battler",
  "Multiplayer online battle arena",
  "Real-time strategy",
  "Real-time tactics",
  "Tower defense",
  "Turn-based strategy",
  "Turn-based tactics",
];

const commaSeparatedList = list.join(", ");
console.log(commaSeparatedList); // Output: "Action, Beat 'em up, Hack and slash, Fighting, Platform, Shooter, Survival, Battle royale, Action-adventure, Stealth, Adventure, Interactive fiction, Interactive movie, Visual novel, Gacha, Horror, Survival horror, Masocore, Massively multiplayer online, Role-playing, Action role-playing, Tactical role-playing, Simulation, Construction and management, Life simulation, Sports, Vehicle, Strategy, 4X, Auto battler, Multiplayer online battle arena, Real-time strategy, Real-time tactics, Tower defense, Turn-based strategy, Turn-based tactics"
